version: 2.1

executors:
  java-executor:
    environment:
      SPRING_DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/project_watcher
      SPRING_DATABASE_USERNAME: postgres
      SPRING_DATABASE_PASSWORD: postgres
    docker:
      - image: circleci/openjdk:8-jdk
      - image: postgres:11.7-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: project_watcher

orbs:
  maven: circleci/maven@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java-executor



