version: 2.1
executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          DATABASE_URL: jdbc:postgressql://postgres:postgres@localhost/project_watcher
      - image: postgres:11.7-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: project_watcher
orbs:
  maven: circleci/maven@1.0.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java-executor
          


      