--liquibase formatted sql

--changeset scholanova:1
CREATE TABLE IF NOT EXISTS MOVIES (
  MOVIE_ID                 SERIAL PRIMARY KEY,
  ADD_DATE				  DATE NOT NULL,
  API_FILM_ID			  NUMERIC,
  LIST_ID				  NUMERIC NOT NULL,
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (MOVIE_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);