--liquibase formatted sql

--changeset scholanova:7
CREATE TABLE IF NOT EXISTS USERSLISTS (
  USERLIST_ID                 SERIAL PRIMARY KEY,
  USER_ID				      INTEGER NOT NULL,
  LIST_ID                     INTEGER NOT NULL
);

ALTER TABLE USERSLISTS
ADD CONSTRAINT constraint_userslists FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE USERSLISTS
ADD CONSTRAINT constraint_userslists2 FOREIGN KEY (LIST_ID) REFERENCES LISTS (LIST_ID);