--liquibase formatted sql

--changeset scholanova:7
CREATE TABLE IF NOT EXISTS MOVIESLISTS (
  MOVIELIST_ID                 SERIAL PRIMARY KEY,
  MOVIE_ID				      INTEGER NOT NULL,
  LIST_ID                     INTEGER NOT NULL
);

ALTER TABLE MOVIESLISTS
ADD CONSTRAINT constraint_movieslists FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (MOVIE_ID);

ALTER TABLE MOVIESLISTS
ADD CONSTRAINT constraint_movieslists2 FOREIGN KEY (LIST_ID) REFERENCES LISTS (LIST_ID);


ALTER TABLE USERS
ADD CONSTRAINT constraint_users FOREIGN KEY (USERLIST_ID) REFERENCES USERSLISTS (USERLIST_ID);

ALTER TABLE MOVIES
ADD CONSTRAINT constraint_movies FOREIGN KEY (MOVIELIST_ID) REFERENCES MOVIESLISTS (MOVIELIST_ID);